[package]
name = "captcha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = {version = "0.28"}
proton-api-rs = {version ="0.10", features=["http-ureq"], path = "../../"}
env_logger = "0.10"
