[package]
name = "you-have-mail-mobile"
version = "0.9.0"
edition = "2021"
authors = ["Leander Beernaert <lbb-dev@pm.me>"]
license = "AGPL-3.0-only"
categories = ["email", "api-bindings"]
readme = "README.md"
description= "You-Have-Mail mobile API bindings"

[lib]
crate-type = ["cdylib"]
name = "youhavemail"

[dependencies]
uniffi = "0.23.0"
you-have-mail-common = {git= "https://github.com/LeanderBB/you-have-mail-common" }
thiserror = "1"
parking_lot = "0.12"
log4rs = "1"

[features]
default = []
null_backend =[]

[build-dependencies]
uniffi = {version ="0.23.0", features=["build", "cli"]}

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"