name: Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name : Get sources
        uses: actions/checkout@v3

      - name: Setup Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.83.0

      - name: Run Tests
        working-directory: you-have-mail-mobile
        run: cargo build


  fmt:
    name: Rustmft
    runs-on: ubuntu-latest
    steps:
      - name : Get sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        working-directory: you-have-mail-mobile
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name : Get sources
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        working-directory: you-have-mail-mobile
        run: cargo clippy -- -D warnings

